#!/usr/bin/env python3
"""Create standardized ChatGPT-readable GitHub workflow reports and retention cleanup plans.

Modes:
- workflow-run: read a GitHub workflow_run event payload and write one workflow_report.md.
- cleanup: scan committed workflow_report.md files plus cleanup-managed staging paths and create an age-based cleanup plan.

Design rule: failure reports must include bounded diagnostic excerpts when log data is available,
so ChatGPT can troubleshoot without operator screenshots, pasted logs, or uploaded logs.

Reports generated by workflow-run mode are completed-run summaries. They are not
live heartbeat polling targets. Active ChatGPT-staged jobs should be monitored via
request_id heartbeat reports outside repo-workflows/.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import subprocess
from pathlib import Path
from typing import Iterable

REPORT_ROOT = Path("chatgpt_staging/status_reports")
REQUEST_ROOT = Path("chatgpt_staging/requests")
OUT_ROOT = Path("chatgpt_staging/out")
SAFE_SEGMENT_RE = re.compile(r"[^A-Za-z0-9._-]+")


def utc_now() -> dt.datetime:
    return dt.datetime.now(dt.timezone.utc)


def iso(ts: dt.datetime) -> str:
    return ts.astimezone(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def safe_segment(value: object, default: str = "unknown") -> str:
    text = str(value or default).strip() or default
    text = SAFE_SEGMENT_RE.sub("-", text)
    text = text.strip(".-_") or default
    return text[:120]


def read_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def read_text_if_present(path: Path | None, limit_chars: int = 60000) -> str:
    if path is None or not path.is_file():
        return ""
    text = path.read_text(encoding="utf-8", errors="replace")
    if len(text) > limit_chars:
        return text[-limit_chars:]
    return text


def bounded_lines(text: str, max_lines: int, max_chars: int) -> list[str]:
    if not text:
        return []
    lines = text.splitlines()
    selected = lines[-max_lines:] if len(lines) > max_lines else lines
    joined = "\n".join(selected)
    if len(joined) > max_chars:
        joined = joined[-max_chars:]
        selected = ["[truncated to final bounded excerpt]"] + joined.splitlines()
    if len(lines) > max_lines:
        selected = [f"[truncated: showing final {len(selected)} of {len(lines)} log lines]"] + selected
    return selected


def git_commit_epoch(path: Path) -> int | None:
    try:
        out = subprocess.check_output(
            ["git", "log", "-1", "--format=%ct", "--", str(path)],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return None
    if not out:
        return None
    try:
        return int(out)
    except ValueError:
        return None


def parse_report_result(path: Path) -> str:
    try:
        text = path.read_text(encoding="utf-8", errors="replace").lower()
    except Exception:
        return "unknown"
    if "- result: failure" in text or "- conclusion: failure" in text:
        return "failure"
    if "- result: cancelled" in text or "- conclusion: cancelled" in text:
        return "failure"
    if "- result: timed_out" in text or "- conclusion: timed_out" in text:
        return "failure"
    if "- result: action_required" in text or "- conclusion: action_required" in text:
        return "failure"
    if "- result: startup_failure" in text or "- conclusion: startup_failure" in text:
        return "failure"
    if "- result: success" in text or "- conclusion: success" in text:
        return "success"
    if "chatgpt-report-retention-cleanup" in text or "retention-cleanup" in str(path):
        return "cleanup"
    return "unknown"


def path_age_days(path: Path, now: dt.datetime) -> float:
    epoch = git_commit_epoch(path)
    if epoch is None:
        return 0.0
    committed = dt.datetime.fromtimestamp(epoch, tz=dt.timezone.utc)
    return max(0.0, (now - committed).total_seconds() / 86400.0)


def newest_report_per_workflow(paths: Iterable[Path]) -> set[Path]:
    newest: dict[str, tuple[int, Path]] = {}
    for path in paths:
        parts = path.parts
        try:
            idx = parts.index("repo-workflows")
            workflow = parts[idx + 1]
        except Exception:
            workflow = str(path.parent)
        epoch = git_commit_epoch(path) or 0
        if workflow not in newest or epoch > newest[workflow][0]:
            newest[workflow] = (epoch, path)
    return {item[1] for item in newest.values()}


def make_workflow_report(args: argparse.Namespace) -> int:
    event_path = Path(args.event_json or os.environ.get("GITHUB_EVENT_PATH", ""))
    if not event_path.is_file():
        raise SystemExit(f"Missing GitHub event JSON: {event_path}")

    event = read_json(event_path)
    run = event.get("workflow_run") or {}
    workflow_name = run.get("name") or args.workflow_name or "unknown-workflow"
    workflow_safe = safe_segment(workflow_name)
    run_id = str(run.get("id") or args.run_id or os.environ.get("GITHUB_RUN_ID", "unknown-run"))
    run_safe = safe_segment(run_id)
    conclusion = str(run.get("conclusion") or "unknown")
    event_name = str(run.get("event") or "unknown")
    head_branch = str(run.get("head_branch") or "")
    head_sha = str(run.get("head_sha") or "")
    html_url = str(run.get("html_url") or "")
    run_attempt = str(run.get("run_attempt") or "")
    run_number = str(run.get("run_number") or "")
    created_at = str(run.get("created_at") or "")
    updated_at = str(run.get("updated_at") or "")
    actor = ((run.get("actor") or {}).get("login") or "unknown") if isinstance(run.get("actor"), dict) else "unknown"
    repository = ((run.get("repository") or {}).get("full_name") or os.environ.get("GITHUB_REPOSITORY", "unknown")) if isinstance(run.get("repository"), dict) else os.environ.get("GITHUB_REPOSITORY", "unknown")

    out_dir = REPORT_ROOT / "repo-workflows" / workflow_safe / run_safe
    out_dir.mkdir(parents=True, exist_ok=True)
    report_path = out_dir / "workflow_report.md"

    failure_conclusions = {"failure", "cancelled", "timed_out", "action_required", "startup_failure"}
    result = "success" if conclusion == "success" else "failure" if conclusion in failure_conclusions else conclusion
    if result == "success":
        action_hint = "No repair needed; review changed paths/artifacts if this workflow protects a code, docs, packaging, or operational surface. Do not use this completed-run summary for live polling; active ChatGPT-staged jobs must be monitored through their live-heartbeat request_id report."
    elif result == "skipped":
        action_hint = "No repair is implied by a skipped conclusion. Confirm the skip condition matches the workflow's trigger or guard, then continue with the next applicable validation signal. Do not use this completed-run summary for live polling; active ChatGPT-staged jobs must be monitored through their live-heartbeat request_id report."
    else:
        action_hint = "Use the embedded bounded log excerpt first. If it is not enough, open workflow_run_url for full GitHub Actions logs/artifacts before asking the operator for screenshots or pasted logs. Do not use this completed-run summary for live polling; active ChatGPT-staged jobs must be monitored through their live-heartbeat request_id report."

    log_file = Path(args.log_file) if args.log_file else None
    log_error_file = Path(args.log_error_file) if args.log_error_file else None
    log_text = read_text_if_present(log_file, limit_chars=args.max_log_chars * 2)
    log_fetch_error = read_text_if_present(log_error_file, limit_chars=12000)
    log_excerpt = bounded_lines(log_text, args.max_log_lines, args.max_log_chars)

    lines = [
        "# ChatGPT workflow report",
        "",
        "## Result",
        "",
        f"- workflow: {workflow_name}",
        "- report_scope: repo-workflows",
        "- report_family: completed-run-summary",
        "- assistant_polling_target: false",
        "- identifier_type: github_run_id",
        "- do_not_use_for_live_polling: true",
        "- live_heartbeat_report_scope: progressive-in-session",
        f"- result: {result}",
        f"- conclusion: {conclusion}",
        f"- source_event: {event_name}",
        f"- workflow_run_id: {run_id}",
        f"- workflow_run_number: {run_number}",
        f"- workflow_run_attempt: {run_attempt}",
        f"- workflow_run_url: {html_url}",
        f"- repository: {repository}",
        f"- head_branch: {head_branch}",
        f"- head_sha: {head_sha}",
        f"- actor: {actor}",
        f"- source_created_at: {created_at}",
        f"- source_updated_at: {updated_at}",
        f"- reporter_run_id: {os.environ.get('GITHUB_RUN_ID', 'unknown')}",
        f"- reporter_sha: {os.environ.get('GITHUB_SHA', 'unknown')}",
        f"- report_created_utc: {iso(utc_now())}",
        "",
        "## Report routing",
        "",
        "This is a completed workflow_run summary under repo-workflows. Use it after a workflow has completed, especially for bounded failure-log excerpts. For active ChatGPT-staged jobs, poll the live-heartbeat report path by request_id instead.",
        "",
        "## Troubleshooting context",
        "",
        "This report was generated by the central ChatGPT workflow-run reporter after the source workflow completed.",
    ]
    if result == "skipped":
        lines += [
            "The source workflow was skipped. This report does not embed a failure log excerpt because a skipped conclusion is not a failure by itself.",
        ]
    elif result != "success":
        lines += [
            "The report includes bounded log context when GitHub log retrieval succeeded. Use the workflow_run_url for full logs/artifacts when deeper detail is required.",
            "",
            "### Bounded source workflow log excerpt",
            "",
        ]
        if log_excerpt:
            lines.append("```text")
            lines.extend(log_excerpt)
            lines.append("```")
        else:
            lines.append("No source workflow log excerpt was available to embed.")
        if log_fetch_error:
            lines += [
                "",
                "### Log retrieval notes",
                "",
                "```text",
                *bounded_lines(log_fetch_error, 80, 12000),
                "```",
            ]
    else:
        lines.append("The source workflow completed successfully; no failure log excerpt is embedded by default.")
    lines += [
        "",
        "## Next ChatGPT action",
        "",
        action_hint,
        "",
        "## Cleanup guidance",
        "",
        "This report is managed by chatgpt-report-retention-cleanup. Success reports, stale staged requests, and aged staged output bundles normally expire by policy.",
    ]
    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(report_path)
    return 0


def make_cleanup_plan(args: argparse.Namespace) -> int:
    now = utc_now()
    root = REPORT_ROOT
    root.mkdir(parents=True, exist_ok=True)
    reports = sorted(root.glob("**/workflow_report.md"))
    request_files = sorted(p for p in REQUEST_ROOT.glob("**/*.json") if p.is_file())
    out_dirs = sorted(p for p in OUT_ROOT.iterdir() if p.is_dir()) if OUT_ROOT.exists() else []

    newest_keep = newest_report_per_workflow(reports) if args.keep_latest else set()
    remove: list[tuple[Path, str, float, str]] = []
    keep: list[tuple[Path, str, float, str]] = []

    for path in reports:
        if path.name != "workflow_report.md":
            continue
        age = path_age_days(path, now)
        if args.workflow_filter and args.workflow_filter not in str(path):
            keep.append((path, "filtered", age, "workflow_filter did not match"))
            continue
        if path in newest_keep:
            keep.append((path, parse_report_result(path), age, "latest report for workflow"))
            continue
        result = parse_report_result(path)
        threshold = args.failure_days if result == "failure" else args.cleanup_days if "cleanup" in str(path) else args.success_days
        if age >= threshold:
            remove.append((path, result, age, f"age {age:.1f}d >= {threshold}d"))
        else:
            keep.append((path, result, age, f"age {age:.1f}d < {threshold}d"))

    for path in request_files:
        age = path_age_days(path, now)
        if args.workflow_filter and args.workflow_filter not in str(path):
            keep.append((path, "request", age, "workflow_filter did not match"))
            continue
        if age >= args.request_days:
            remove.append((path, "request", age, f"age {age:.1f}d >= {args.request_days}d"))
        else:
            keep.append((path, "request", age, f"age {age:.1f}d < {args.request_days}d"))

    for path in out_dirs:
        age = path_age_days(path, now)
        if args.workflow_filter and args.workflow_filter not in str(path):
            keep.append((path, "bundle", age, "workflow_filter did not match"))
            continue
        if age >= args.bundle_days:
            remove.append((path, "bundle", age, f"age {age:.1f}d >= {args.bundle_days}d"))
        else:
            keep.append((path, "bundle", age, f"age {age:.1f}d < {args.bundle_days}d"))

    removed_file = Path(args.removed_paths_file)
    removed_file.parent.mkdir(parents=True, exist_ok=True)
    if args.dry_run:
        removed_file.write_text("", encoding="utf-8")
    else:
        removed_file.write_text("\n".join(str(p) for p, _, _, _ in remove) + ("\n" if remove else ""), encoding="utf-8")

    lines = [
        "# ChatGPT workflow report",
        "",
        "## Result",
        "",
        "- workflow: chatgpt-report-retention-cleanup",
        "- report_scope: retention-cleanup",
        "- report_family: retention-cleanup-summary",
        "- assistant_polling_target: false",
        "- identifier_type: cleanup_run_id",
        "- do_not_use_for_live_polling: true",
        "- result: success",
        f"- mode: {'dry-run' if args.dry_run else 'delete'}",
        f"- success_retention_days: {args.success_days}",
        f"- failure_retention_days: {args.failure_days}",
        f"- cleanup_retention_days: {args.cleanup_days}",
        f"- request_retention_days: {args.request_days}",
        f"- bundle_retention_days: {args.bundle_days}",
        f"- keep_latest_per_workflow: {str(args.keep_latest).lower()}",
        f"- workflow_filter: {args.workflow_filter or ''}",
        f"- candidate_count: {len(remove)}",
        f"- retained_count: {len(keep)}",
        f"- github_run_id: {os.environ.get('GITHUB_RUN_ID', 'unknown')}",
        f"- github_sha: {os.environ.get('GITHUB_SHA', 'unknown')}",
        f"- report_created_utc: {iso(now)}",
        "",
        "## Paths selected for cleanup" if not args.dry_run else "## Paths that would be cleaned",
    ]
    if remove:
        for path, kind, age, reason in remove:
            lines.append(f"- `{path}` | kind={kind} | age_days={age:.1f} | reason={reason}")
    else:
        lines.append("- none")
    lines += ["", "## Paths retained or skipped"]
    if keep:
        for path, kind, age, reason in keep[:200]:
            lines.append(f"- `{path}` | kind={kind} | age_days={age:.1f} | reason={reason}")
        if len(keep) > 200:
            lines.append(f"- ... {len(keep) - 200} additional retained paths omitted from summary")
    else:
        lines.append("- none")
    lines += [
        "",
        "## Next ChatGPT action",
        "",
        "Read this cleanup report, verify scoped deletion/readback when cleanup was not a dry run, then record Airtable evidence if material. Do not use retention-cleanup reports for live workflow polling.",
    ]
    cleanup_report.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(cleanup_report)
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="mode", required=True)

    wr = sub.add_parser("workflow-run")
    wr.add_argument("--event-json")
    wr.add_argument("--workflow-name")
    wr.add_argument("--run-id")
    wr.add_argument("--log-file", default="")
    wr.add_argument("--log-error-file", default="")
    wr.add_argument("--max-log-lines", type=int, default=300)
    wr.add_argument("--max-log-chars", type=int, default=40000)
    wr.set_defaults(func=make_workflow_report)

    cl = sub.add_parser("cleanup")
    cl.add_argument("--success-days", type=int, default=1)
    cl.add_argument("--failure-days", type=int, default=7)
    cl.add_argument("--cleanup-days", type=int, default=2)
    cl.add_argument("--request-days", type=int, default=1)
    cl.add_argument("--bundle-days", type=int, default=2)
    cl.add_argument("--workflow-filter", default="")
    cl.add_argument("--report-id", default="")
    cl.add_argument("--removed-paths-file", default=".github/tmp/chatgpt_report_cleanup_removed.txt")
    cl.add_argument("--dry-run", action="store_true")
    cl.add_argument("--keep-latest", action="store_true", default=True)
    cl.set_defaults(func=make_cleanup_plan)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
