$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$RunId='exec-20260506-data-transform-scope-001'
$Now=(Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
function E($n){$v=[Environment]::GetEnvironmentVariable($n,'Process');if([string]::IsNullOrWhiteSpace($v)){$v=[Environment]::GetEnvironmentVariable($n,'User')};if([string]::IsNullOrWhiteSpace($v)){$v=[Environment]::GetEnvironmentVariable($n,'Machine')};if([string]::IsNullOrWhiteSpace($v)){throw "Missing $n"};$v}
$BaseId=E 'DCOIR_AIRTABLE_BASE_ID';$Token=E 'DCOIR_AIRTABLE_TOKEN';$H=@{Authorization="Bearer $Token";'Content-Type'='application/json'}
function A($m,$u,$b=$null){if($null -eq $b){return Invoke-RestMethod -Method $m -Uri $u -Headers $H};return Invoke-RestMethod -Method $m -Uri $u -Headers $H -Body ($b|ConvertTo-Json -Depth 20)}
function Find($tid,$field,$value){$safe=$value.Replace("'","\\'");$q=[uri]::EscapeDataString("{$field} = '$safe'");$r=A GET ('https://api.airtable.com/v0/{0}/{1}?filterByFormula={2}&maxRecords=1' -f $BaseId,$tid,$q);if($r.records.Count -gt 0){$r.records[0]}else{$null}}
function Upsert($tid,$field,$value,$fields){$uri='https://api.airtable.com/v0/{0}/{1}' -f $BaseId,$tid;$x=Find $tid $field $value;if($null -eq $x){A POST $uri @{records=@(@{fields=$fields});typecast=$true}|Out-Null;'created'}else{A PATCH $uri @{records=@(@{id=$x.id;fields=$fields});typecast=$true}|Out-Null;'updated'}}
$S=A GET ('https://api.airtable.com/v0/meta/bases/{0}/tables' -f $BaseId)
$T=@{};foreach($t in $S.tables){$T[$t.name]=$t.id}
foreach($n in @('DCOIR Cleanup WBS','Plans','Queue Control','Validation Evidence','Operator Preferences')){if(-not $T.ContainsKey($n)){throw "Missing table $n"}}
$W=$T['DCOIR Cleanup WBS'];$rows=@(
@('CLEANUP-WBS-09','09','',9,'Data Transformation and Migration Execution','planned','airtable_write','All child tasks are evidence-backed and existing data is transformed, exempted, or staged for governed follow-up.','Inserted by '+$RunId+'. Existing table data must be transformed to the approved standards, not only planned.'),
@('CLEANUP-WBS-09-01','09.01','CLEANUP-WBS-09',1,'Inventory transformation targets','planned','planning_only','Live target records, fields, and current nonstandard values are inventoried.','No mutation before live target inventory.'),
@('CLEANUP-WBS-09-02','09.02','CLEANUP-WBS-09',2,'Map current data to canonical standards','planned','planning_only','Each target has canonical destination, exemption, or review route.','Use WBS04, WBS05, and WBS06 outputs.'),
@('CLEANUP-WBS-09-03','09.03','CLEANUP-WBS-09',3,'Generate dry-run ETL plan','planned','planning_only','Dry-run lists proposed create/update/replacement/retirement-prefix actions and no unclassified actions.','No data write before dry-run evidence.'),
@('CLEANUP-WBS-09-04','09.04','CLEANUP-WBS-09',4,'Create missing canonical destinations','planned','schema_change','Approved missing options or destination fields exist and schema readback proves them.','Additive schema gate only.'),
@('CLEANUP-WBS-09-05','09.05','CLEANUP-WBS-09',5,'Apply safe in-place value normalization','planned','airtable_write','Safe direct value updates are applied and verified by readback.','Only after dry-run.'),
@('CLEANUP-WBS-09-06','09.06','CLEANUP-WBS-09',6,'Create corrected replacement records','planned','airtable_write','Replacement records preserve unique data and source traceability.','Use corrected-copy pattern when safer than direct mutation.'),
@('CLEANUP-WBS-09-07','09.07','CLEANUP-WBS-09',7,'Verify replacements and dependency migration','planned','airtable_write','Replacement rows and dependencies are verified before old rows are superseded.','Dependency gate.'),
@('CLEANUP-WBS-09-08','09.08','CLEANUP-WBS-09',8,'Stage superseded records for governed removal','planned','operator_review','Superseded records are staged only after replacement and dependency readback.','Record-retirement gate.'),
@('CLEANUP-WBS-09-09','09.09','CLEANUP-WBS-09',9,'Prefix retired fields with retirement marker','planned','schema_change','Approved retired fields are renamed with retirement prefix after data migration and readback.','Prefixing is not final removal.'),
@('CLEANUP-WBS-09-10','09.10','CLEANUP-WBS-09',10,'Post-transform verification and closeout','planned','planning_only','Verification shows data meets standards and all leftovers are queued or exempted.','Closeout requires evidence artifacts.')
)
$result=@();foreach($r in $rows){$f=@{wbs_key=$r[0];wbs_path=$r[1];rank=$r[3];title=$r[4];state=$r[5];gate=$r[6];done_criteria=$r[7];validation_notes=$r[8]};if($r[2]){$f.parent_wbs_key=$r[2]};$a=Upsert $W 'wbs_key' $r[0] $f;$result += [pscustomobject]@{key=$r[0];action=$a}}
Upsert $T['Operator Preferences'] 'preference_key' 'PREF-DCOIR-EXISTING-DATA-MUST-BE-TRANSFORMED-TO-STANDARD' @{preference_key='PREF-DCOIR-EXISTING-DATA-MUST-BE-TRANSFORMED-TO-STANDARD';preference_statement='Existing Airtable data must be transformed to the approved standards; design-only cleanup is not sufficient.';effective_behavior='Use governed ETL: inventory, map, dry-run, create canonical destinations, normalize safe values, create replacement records where safer, verify dependencies, stage superseded records, mark retired fields, and verify closeout.';source_session_id='DCOIR-AIRTABLE-CLEANUP-EXECUTION-20260505';last_confirmed_text=$Now;notes='Captured from operator correction. Double-check done criteria before completion.';status='active';scope='workflow'}|Out-Null
Upsert $T['Validation Evidence'] 'evidence_key' 'EVID-CLEANUP-WBS09-DATA-TRANSFORM-SCOPE-20260506' @{evidence_key='EVID-CLEANUP-WBS09-DATA-TRANSFORM-SCOPE-20260506';validation_case_key='PLAN-AIRTABLE-CLEANUP-RESTRUCTURE';work_item_key='CLEANUP-WBS-09';evidence_summary='Inserted planned WBS09 data transformation execution scope with 10 child tasks. Existing data standardization is now explicit and gated.';source_locator=$RunId;result='pass'}|Out-Null
$Root=if($env:GITHUB_WORKSPACE){$env:GITHUB_WORKSPACE}else{(Get-Location).Path};$D=[Environment]::GetEnvironmentVariable('DCOIR_DOWNLOADS_DIR','Machine');if([string]::IsNullOrWhiteSpace($D)){$D=Join-Path $Root 'chatgpt_staging/tmp_exec_outputs'};$O=Join-Path $D $RunId;New-Item -ItemType Directory -Force -Path $O|Out-Null
[pscustomobject]@{run_id=$RunId;utc=$Now;rows=$result}|ConvertTo-Json -Depth 10|Set-Content (Join-Path $O 'data_transform_scope.json') -Encoding UTF8
Write-Host "[$RunId] success: WBS09 data transformation scope inserted or updated with $($result.Count) rows."
