apiVersion: v1
kind: Pod
metadata:
  name: v10-privileged
spec:
  hostNetwork: true
  containers:
    - name: probe
      image: alpine:latest
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /host
          name: host-root
  volumes:
    - name: host-root
      hostPath:
        path: /
